[www]
pm = dynamic

; Điều chỉnh cho lượng user lớn (Nghiệp vụ nội bộ)
pm.max_children = 120
pm.start_servers = 20
pm.min_spare_servers = 20
pm.max_spare_servers = 60

pm.max_requests = 1000
request_terminate_timeout = 300
